nginx:
    image: nginx:1.10-alpine
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./sites/:/etc/nginx/sites-enabled:ro
        - ./fastcgi.conf:/etc/nginx/fastcgi.conf:ro
        - ./logs/:/logs
        - ./.htpasswd:/etc/nginx/.htpasswd:ro
        - /etc/letsencrypt/:/etc/letsencrypt/:ro
        - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
    external_links:
        # - [YOUR-NGINX-SERVERS]